Online_Exam_Project_Main/Controllers/SelectExamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Exam_Project_Main.Models;

namespace Online_Exam_Project_Main.Controllers
{
    public class SelectExamController : Controller
    {
        private Exam_QuizEntities db = new Exam_QuizEntities();
        //
        // GET: /SelectExam/
        public ActionResult Index()
        {
            int count = 0;
            var name = db.Exam_tbl.ToList();
            SelectList list = new SelectList(name, "exam_id", "exam_title");
            DrpList drp = new DrpList();
            drp.Examlist = name;
            drp.QuestionNo = 1;
            ViewBag.name = list;
            Session["name"] = ViewBag.name;




            return View(drp);
        }
        [HttpPost]
        public void SetFromDrp(int val)
        {
            ViewBag.drpVal = val;
        }
	}
}

Online_Exam_Project_Main/Controllers/ShowQuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Exam_Project_Main.Models;

namespace Online_Exam_Project_Main.Controllers
{
    public class ShowQuestionController : Controller
    {
        //
        // GET: /ShowQuestion/
        Exam_QuizEntities db = new Exam_QuizEntities();


        
        [HttpPost]
        public ActionResult Index(DrpList drp)
        {

            ViewBag.drpData = drp;
            ViewBag.questionNo = drp.QuestionNo;

            TempData["a"] = drp.QuestionNo;

            if (drp.QuestionNo == 1)
            //if (questionNo == null || id == null)
            {
                Session["exid"] = drp.examid;

                Questions_tbl SingleQuestion = db.Questions_tbl.SingleOrDefault(m => m.qus_id == 1 && m.exam_id == drp.examid);

                
                TempData["qData"] = SingleQuestion;
                return RedirectToAction("NextQuestion");
                //return View(SingleQuestion);
            }
            else
            {


                Questions_tbl SingleQuestion = db.Questions_tbl.SingleOrDefault(m => m.qus_id == drp.QuestionNo && m.exam_id == drp.examid);
                int qus = (int)drp.QuestionNo;

                //for (int i = 0; i <= drp.QuestionNo; i++)
                //{
                //    ViewBag.questionNo = qusno + i;
                //}


                return View(SingleQuestion);
            }

        }


#pragma warning disable CS0414 // The field 'ShowQuestionController.add' is assigned but its value is never used
        int add = 0;
#pragma warning restore CS0414 // The field 'ShowQuestionController.add' is assigned but its value is never used




        public ActionResult NextQuestion()
        {
            int qNo = (int)TempData["a"];
            ViewBag.questionNo = qNo;
            Questions_tbl a = (Questions_tbl)TempData["qData"];

            return View(a);

        }
        [HttpPost]
        public ActionResult NextQuestion(Questions_tbl aaa)
        {
            if(aaa.qus_id == 1)
            {
                Session["correctAns"] = 0;
            }
            


            if (aaa.correct_ans == aaa.selectedvalue)
            {
                var temp = Session["correctAns"];
                Session["correctAns"] = Convert.ToInt32(Session["correctAns"]) + 1;
            }
            //else if (aaa.correct_ans == aaa.selectedvalue && aaa.qus_id == 1)
            //{
            //    Session["correctAns"] = 1;
            //}

            if (aaa.qus_id == 10)
            {
                var temp = Session["correctAns"];
                return RedirectToAction("Create","Result");

            }
            int qId = (int)aaa.qus_id + 1;
            Questions_tbl SingleQuestion = db.Questions_tbl.SingleOrDefault(m => m.qus_id == qId && m.exam_id == aaa.exam_id);
            
            
            ViewBag.questionNo = qId;
            if(SingleQuestion == null)
            {
                return RedirectToAction("Create","Result");
            }
            TempData["a"] = SingleQuestion.qus_id;
            TempData["qData"] = SingleQuestion;
            return RedirectToAction("NextQuestion");

        }
    }
	}

Online_Exam_Project_Main/Views/SelectExam/Index.cshtml
@model Online_Exam_Project_Main.Models.DrpList

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="color:white">Select Exam</h2>

<div class="col-md-6">

    @using (Html.BeginForm("Index", "ShowQuestion", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            
            <hr />
            @Html.ValidationSummary(true)

            @Html.HiddenFor(m => m.QuestionNo, 1)

            <div class="form-group" style="color:white">
                @Html.Label("Exam ID","Exam Name", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.DropDownList("item1", ViewBag.name as SelectList, "Select Exam")*@

                    @Html.DropDownListFor(m => m.examid, new SelectList(Model.Examlist, "exam_id", "exam_title"), "Select Exam")


                    @Html.ValidationMessageFor(model => model.exam_title)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Start Exam" class="btn btn-default" />

                </div>
            </div>
        </div>
    }
</div>

<div class="col-md-6">
    
    <h2 style="color: white"> <u>Rules</u></h2>
    
    <h3 style="color:white">
        <ul>
            <li>For each question you have only 1 minute.</li><br>
            <li>If you want you can skip question</li><br>
            <li>For each corect answer you have 1 point</li>
        </ul>
    </h3>
</div>
<br>


<style>
    body {
        background-image: url('/Content/image 88.jpg');
        background-repeat: no-repeat;
        background-size: 100% 100%;
        background-attachment: fixed;
    }
</style>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}